# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

#pod 'Leanplum-iOS-SDK'
# pod 'Leanplum-iOS-Location'
pod 'LeanplumSegment', '~> 1.1.1'


target 'basicSetup' do

end

