# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift

target 'fedeTest' do
	use_frameworks!
#    pod 'Leanplum-iOS-SDK', '1.4.2'
#    pod 'Leanplum-iOS-SDK', '1.7.0'
    pod 'Leanplum-iOS-SDK', '2.0.1'
#    pod 'Leanplum-iOS-SDK'
#	pod 'Leanplum-iOS-Location'
end

