# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift

target 'fedeTest' do
	use_frameworks!
	pod 'Leanplum-iOS-SDK', '1.5.1'
	pod 'Leanplum-iOS-Location', '1.5.1'
end

