# Uncomment the next line to define a global platform for your project
platform :tvos, '9.0'

use_frameworks!

target 'fedeTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  
  pod 'Leanplum-iOS-SDK'
  # Pods for fedeTest

end
